name: Calculate Jam Priority Scores

on:
  schedule:
    - cron: '0 2 * * 2'
  workflow_dispatch:

jobs:
  run-priority-update:
    runs-on: ubuntu-latest
    steps:
      - name: Call API and Print Result
        run: |
          echo "Calling calculate-priority..."
          
          # -f makes the step fail immediately on 4xx or 5xx errors
          curl -f -s -X POST "https://subumbelliferous-geraldine-pactional.ngrok-free.dev/api/public/calculate-priority" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json"

          echo "Priority calculation finished successfully"
